openapi: "3.0.0"
info:
  version: 1.0.0
  title: Knot.x Starter Kit
  description: Knotx Starter Kit

servers:
  - url: https://{domain}:{port}
    description: The local API server
    variables:
      domain:
        default: localhost
        description: api domain
      port:
        enum:
          - '8092'
        default: '8092'

paths:
  /api/hello:
    get:
      operationId: hello-world-operation
      responses:
        default:
          description: Example API implemented in this tutorial
  /healthcheck:
    get:
      operationId: healthcheck-operation
      # https://vertx.io/docs/vertx-health-check/java/
      responses:
        '200':
          description: Everything is fine
        '204':
          description: No procedure are registered.
        '501':
          description: At least one procedure has reported a non-healthy stat
        '500':
          description: One procedure has thrown an error or has not reported a status in time
