openapi: "3.0.0"
info:
  version: 1.0.0
  title: Knot.x GraphQL Example
  description: Knot.x GraphQL Example

servers:
  - url: https://{domain}:{port}
    description: The local API server
    variables:
      domain:
        default: localhost
        description: api domain
      port:
        enum:
          - '8092'
        default: '8092'

paths:
  /healthcheck:
    get:
      operationId: healthcheck-operation
      responses:
        default:
          description: example vert.x healthcheck

  /api/graphql:
    post:
      operationId: books-gql-operation
      responses:
        default:
          description: Books Graphql API
