version: '3.7'

networks:
  knotnet:

services:
  repository:
    image: httpd:2.4
    volumes:
      - "./example-data/content/public_html:/usr/local/apache2/htdocs"
    ports:
      - "4503:80"
    networks:
      - knotnet

  webapi:
    image: rodolpheche/wiremock
    volumes:
      - "./example-data/webapi:/home/wiremock"
    ports:
      - "3000:8080"
    networks:
      - knotnet

  knotx:
    image: knotx/knotx:2.2.0
    command: ["knotx", "run-knotx"]
    volumes:
      - "./knotx/conf:/usr/local/knotx/conf"
    ports:
      - "8092:8092"
      - "18092:18092"
    networks:
      - knotnet