openapi: "3.0.0"
info:
  version: 1.0.0
  title: Knot.x Gateway API Example
  description: Knot.x Gateway API Example

servers:
  - url: https://{domain}:{port}
    description: The local API server
    variables:
      domain:
        default: localhost
        description: api domain
      port:
        enum:
          - '8092'
        default: '8092'

paths:
  /healthcheck:
    get:
      operationId: healthcheck-operation
      responses:
        default:
          description: example vert.x healthcheck

  /api/v1/payments:
    get:
      operationId: payment-rx-operation
      responses:
        default:
          description: Payments API

  /api/v2/payments:
    get:
      operationId: payment-rx-operation-with-cb
      responses:
        default:
          description: Payments API with fallback

  /api/v3/payments:
    get:
      operationId: payment-configurable-operation
      responses:
        default:
          description: Payments API with configurable task