version: '3.7'

networks:
  knotnet:

services:

  webapi:
    image: rodolpheche/wiremock
    volumes:
      - "../../common-services/webapi:/home/wiremock"
      # Remember to put https://repo1.maven.org/maven2/com/opentable/wiremock-body-transformer/1.1.3/wiremock-body-transformer-1.1.3.jar in ../../common-services/webapi/extensions directory!
      - "../../common-services/webapi/extensions:/var/wiremock/extensions"
    ports:
      - "3000:8080"
    networks:
      - knotnet
    command: ["--global-response-templating", "--extensions", "com.opentable.extension.BodyTransformer"]

  knotx:
    image: knotx-example/api-cache:latest
    command: ["knotx", "run-knotx"]
    ports:
      - "8092:8092"
      - "18092:18092"
    networks:
      - knotnet
