version: '3'

services:
  core:
    build: ./core
    image: acme-core:latest
    ports:
      - "8092:8092"
  data-bridge-adapter:
    build: dataSourceHttp
    image: acme-data-bridge-adapter:latest
  forms-adapter:
    build: ./formsAdapter
    image: acme-action-adapter:latest
  fs-repo:
    build: ./fsRepo
    image: acme-fs-repo:latest
  gateway:
    build: ./gateway
    image: acme-gateway:latest
  hbs-1:
    build: ./handlebars
    image: acme-handlebars-1:latest
    command: ["run-knotx", "-ha", "--hagroup hbs-group", "--quorum 2"]
  hbs-2:
    build: ./handlebars
    image: acme-handlebars-2:latest
    command: ["run-knotx", "-ha", "--hagroup hbs-group", "--quorum 2"]
  hbs-bare:
    build: ./handlebars
    image: acme-handlebars-bare:latest
    command: ["bare", "--hagroup hbs-group", "--quorum 2"]
  repo-mock:
    build: ./repoMock
    image: acme-repo-mock:latest
  service-mock:
    build: ./serviceMock
    image: acme-service-mock:latest
