openapi: 3.0.0
info:
  version: 1.0.0
  title: Knot.x Starter Kit Docker example
  description: Knotx Starter Kit Docker example
  contact:
    name: "Knot.x Community"
    url: "http://knotx.io/community/"

servers:
  - url: https://{domain}:{port}
    description: The local API server
    variables:
      domain:
        default: localhost
        description: api domain
      port:
        enum:
          - '8092'
        default: '8092'

paths:
  /api/secure/basic:
    get:
      operationId: hello-world-operation-basic
      security:
        - helloBasicAuth: []
      responses:
        '200':
          description: Hello World API protected with Basic Auth
        '401':
          description: Anauthorized access
  /api/secure/jwt:
    get:
      operationId: hello-world-operation-jwt
      security:
          - helloJwtAuth: []
      responses:
        '200':
          description: Hello World API protected with JWT
        '401':
          description: Anauthorized access

components:
  securitySchemes:
    helloBasicAuth:
      type: http
      scheme: basic
    helloJwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
