name: Verify examples

on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/gradle-build-action@v2
    - name: "Build: Distribution -> Getting Started with Stack"
      run: ./distribution/getting-started/gradlew -p ./distribution/getting-started build --info